#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


sh $HOME/.screenlayout/setup_monitors

#boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  killall picom
  picom --shadow-exclude argb -b -f &> /dev/null &
fi
if [ -x s"$(command -v dunst)" ]; then
  dunst
fi

#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill $HOME/.screenlayout/wallpapers/hor/1.jpg $HOME/.screenlayout/wallpapers/vert/0.jpg
fi

index=0
monitors="$(polybar -m | sed s/:.*//)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  let indextemp=index+1
  monitor=$(sed "$indextemp!d" <<<"$monitors")
  barname="redbar$index"
  monitor=$monitor offset=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  let index=indextemp
done

